import os
from shutil import move
import argparse


"""
This program seperate a 'chemical' subset into chemical and manychemical datapoints
It reads counts from a countfile, which is generated by some external tool

INPUT:
    -countfile: path to file that contains the chemical structure counts for a set of images
    -datasetpath: path to the chemical dataset folder
OUTPUT:
    Will generate a new folder called 'manychemical', containing the images that have more than one chemical structure according to the countfile

Can be ran as: 'python -m manychem_seperator -countfile=path/to/countfile -datasetpath=path/to/dataset'
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-countfile', 'Provide path to file that contains structure counts', required=True)
    parser.add_argument('-datasetpath', 'Provide path to directory that contains chem/nonchem dataset', required=True)
    parsed_args = parser.parse_args()

    countfile_path = parsed_args.countfile
    dataset_path = parsed_args.datasetpath

    with open(countfile_path, 'r') as f:
        data = [x.split('\t') for x in  f.read().split('\n')[1:]]

    # Create the manychemical subfolder if not exists
    if not os.path.isdir(os.path.join(dataset_path, 'manychemical')):
        os.makedirs(os.path.join(dataset_path, 'manychemical'))

    chemicals = os.listdir(os.path.join(dataset_path, 'chemical'))

    # Move every image that is a chemical into the 'manychemical' subfolder, if the countfile data > 1
    for image, counts in data:
        if image+'.TIF' in chemicals and counts > '1':
            move(os.path.join(dataset_path, 'chemical', image+'.TIF'), os.path.join(dataset_path, 'manychemical'))

    print(f'Finished extracting the image that contain multiple chemical structure, into {dataset_path}/manychemical')